version: '3.8'

services:
  nginx:
    restart: always
    image: trunkplayer/trunkplayer-ng-nginx:latest
    ports:
      - 80:80
      - 443:443
    depends_on:
      - trunk-player
    volumes:
      - /tmp/static:/code/static
      - /tmp/media:/code/mediafiles

  trunk-player:
    restart: always
    image: trunkplayer/trunkplayer-ng:latest
    command: "bash -c 'python -m gevent.monkey manage.py migrate; python -m gevent.monkey manage.py createsuperuser --noinput; python -m gevent.monkey manage.py collectstatic --no-input; uwsgi --ini /code/uwsgi.conf'"
    environment:
      DEBUG: "False"
      SEND_TELEMETRY: "False"
      FORCE_SECURE: "False"
      SECRET_KEY: 9fwg4f0734gh0t8hyf3028y4hgf037w4tyhtr579435ty9h45098h
      SQL_DATABASE: trunkplayerng
      SQL_USER: TrunkPlayer
      SQL_PASSWORD: CHANGEME
      SQL_HOST: mysql
      TZ: America/Chicago
      CELERY_BROKER_URL: amqp://trunkplayer:CHANGEME@rabbitmq:5672/
      USE_S3: "False"
      AUDIO_DOWNLOAD_HOST: "https://your.site"
      S3_ACCESS_KEY_ID: "ACCESS_KEY"
      S3_SECRET_ACCESS_KEY: "I_AM_AN_ID10T"
      S3_BUCKET_NAME: "BUCKET_NAME"
      S3_ENDPOINT_URL: "https://s3.us-west-1.amazonaws.com"
      DJANGO_SUPERUSER_PASSWORD: "password"
      DJANGO_SUPERUSER_EMAIL: "admin@example.com"
    volumes:
      #  - /run/mysqld/mysqld.sock:/run/mysqld/mysqld.sock (Use me for system sql)
      - /tmp/static:/code/static
      - /tmp/media:/code/mediafiles
    depends_on:
      - mysql
      - rabbitmq

  trunk-player-worker:
    restart: always
    image: trunkplayer/trunkplayer-ng:latest
    command: celery -A trunkplayer_ng worker -l info --pool=gevent --concurrency 100 -Q default,transmission_forwarding,RR_IMPORT,radio_alerts,radio_tx
    environment:
      DEBUG: "False"
      FORCE_SECURE: "False"
      SEND_TELEMETRY: "False"
      SECRET_KEY: 9fwg4f0734gh0t8hyf3028y4hgf037w4tyhtr579435ty9h45098h
      SQL_DATABASE: trunkplayerng
      SQL_USER: TrunkPlayer
      SQL_PASSWORD: CHANGEME
      SQL_HOST: mysql
      TZ: America/Chicago
      CELERY_BROKER_URL: amqp://trunkplayer:CHANGEME@rabbitmq:5672/
      USE_S3: "False"
      S3_ACCESS_KEY_ID: "ACCESS_KEY"
      S3_SECRET_ACCESS_KEY: "I_AM_AN_ID10T"
      S3_BUCKET_NAME: "BUCKET_NAME"
      S3_ENDPOINT_URL: "https://s3.us-west-1.amazonaws.com"
    volumes:
      #  - /run/mysqld/mysqld.sock:/run/mysqld/mysqld.sock (Use me for system sql)
      - /tmp/static:/code/static
      - /tmp/media:/code/mediafiles
    depends_on:
      - mysql
      - rabbitmq

  trunk-player-beat:
    restart: always
    image: trunkplayer/trunkplayer-ng:latest
    command: celery -A trunkplayer_ng beat -l info
    environment:
      DEBUG: "False"
      FORCE_SECURE: "False"
      SEND_TELEMETRY: "False"
      SECRET_KEY: 9fwg4f0734gh0t8hyf3028y4hgf037w4tyhtr579435ty9h45098h
      SQL_DATABASE: trunkplayerng
      SQL_USER: TrunkPlayer
      SQL_PASSWORD: CHANGEME
      SQL_HOST: mysql
      TZ: America/Chicago
      CELERY_BROKER_URL: amqp://trunkplayer:CHANGEME@rabbitmq:5672/
      USE_S3: "False"
      S3_ACCESS_KEY_ID: "ACCESS_KEY"
      S3_SECRET_ACCESS_KEY: "I_AM_AN_ID10T"
      S3_BUCKET_NAME: "BUCKET_NAME"
      S3_ENDPOINT_URL: "https://s3.us-west-1.amazonaws.com"
    volumes:
    #  - /run/mysqld/mysqld.sock:/run/mysqld/mysqld.sock (Use me for system sql) 
      - /tmp/static:/code/static
      - /tmp/media:/code/mediafiles
    depends_on:
      - mysql
      - rabbitmq

  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: CHANGEME
      MYSQL_DATABASE: trunkplayerng
      MYSQL_USER: TrunkPlayer
      MYSQL_PASSWORD: CHANGEME
    volumes:
      - /path/to/db:/var/lib/mysql

  rabbitmq:
    image: 'rabbitmq:management'
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: trunkplayer
      RABBITMQ_DEFAULT_PASS: CHANGEME
        
  
