version: '3.8'

services:
  nginx:
    restart: always
    image: trunkplayer/trunkplayer-ng-nginx:latest
    ports:
      - 80:80
      - 443:443
    depends_on:
      - trunk-player
    volumes:
      - /tmp/static:/code/static
      - /tmp/media:/code/mediafiles

  trunk-player:
    restart: always
    image: trunkplayer/trunkplayer-ng:latest
    command: "bash -c 'sleep 10; python -m gevent.monkey manage.py migrate; python -m gevent.monkey manage.py createsuperuser --noinput; python -m gevent.monkey manage.py collectstatic --no-input; uwsgi --ini /code/uwsgi.conf'"
    volumes:
      #  - /run/mysqld/mysqld.sock:/run/mysqld/mysqld.sock (Use me for system sql)
      - /tmp/static:/code/static
      - /tmp/media:/code/mediafiles
    depends_on:
      - mysql
      - rabbitmq

  trunk-player-worker:
    restart: always
    image: trunkplayer/trunkplayer-ng:latest
    command: celery -A trunkplayer_ng worker -l info --pool=gevent --concurrency 100 -Q default,transmission_forwarding,RR_IMPORT,radio_alerts,radio_tx
    volumes:
      #  - /run/mysqld/mysqld.sock:/run/mysqld/mysqld.sock (Use me for system sql)
      - /tmp/static:/code/static
      - /tmp/media:/code/mediafiles
    depends_on:
      - mysql
      - rabbitmq

  trunk-player-beat:
    restart: always
    image: trunkplayer/trunkplayer-ng:latest
    command: celery -A trunkplayer_ng beat -l info
    volumes:
    #  - /run/mysqld/mysqld.sock:/run/mysqld/mysqld.sock (Use me for system sql) 
      - /tmp/static:/code/static
      - /tmp/media:/code/mediafiles
    depends_on:
      - mysql
      - rabbitmq

  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - /path/to/db:/var/lib/mysql

  rabbitmq:
    image: 'rabbitmq:management'
    restart: always
    ports:
      - "15672:15672"

  
