# Generated by Django 4.1.5 on 2023-01-15 22:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import radio.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('UUID', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('UUID', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalAnnouncement',
            fields=[
                ('UUID', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('enabled', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GlobalEmailTemplate',
            fields=[
                ('UUID', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('template_type', models.CharField(choices=[('welcome', 'welcome'), ('alert', 'alert')], max_length=30, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('HTML', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScanList',
            fields=[
                ('UUID', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('public', models.BooleanField(default=False)),
                ('community_shared', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('UUID', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('rr_system_id', models.CharField(blank=True, max_length=100, null=True)),
                ('enable_talkgroup_acls', models.BooleanField(default=False, verbose_name='Enable Talkgroup ACLs')),
                ('prune_transmissions', models.BooleanField(default=False, verbose_name='Enable Pruneing Transmissions')),
                ('prune_transmissions_after_days', models.IntegerField(default=365, verbose_name='Days to keep Transmissions (Prune)')),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='SystemRecorder',
            fields=[
                ('UUID', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('site_id', models.CharField(blank=True, max_length=100, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('api_key', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.system')),
            ],
        ),
        migrations.CreateModel(
            name='TalkGroup',
            fields=[
                ('UUID', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('decimal_id', models.IntegerField(db_index=True)),
                ('alpha_tag', models.CharField(blank=True, default='', max_length=30)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('mode', models.CharField(choices=[('digital', 'Digital'), ('analog', 'Analog'), ('tdma', 'TDMA'), ('mixed', 'Mixed')], default='digital', max_length=250)),
                ('encrypted', models.BooleanField(blank=True, default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('agency', models.ManyToManyField(blank=True, to='radio.agency')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.system')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('UUID', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('decimal_id', models.IntegerField(db_index=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.system')),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('UUID', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('urgent', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('UUID', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('site_admin', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('site_theme', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInbox',
            fields=[
                ('UUID', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('messages', models.ManyToManyField(to='radio.usermessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserAlert',
            fields=[
                ('UUID', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('web_notification', models.BooleanField(default=False)),
                ('app_rise_notification', models.BooleanField(default=False)),
                ('app_rise_urls', models.TextField(blank=True, default='', verbose_name=', Seperated AppriseURL(s)')),
                ('emergency_only', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=1, verbose_name='Number of Transmissions over trigger time to alert')),
                ('trigger_time', models.IntegerField(default=10, verbose_name='trigger time')),
                ('title', models.CharField(default='New Activity Alert', max_length=255)),
                ('body', models.TextField(default='New Activity on %T - %I')),
                ('talkgroups', models.ManyToManyField(blank=True, to='radio.talkgroup')),
                ('units', models.ManyToManyField(blank=True, to='radio.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='radio.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('UUID', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('audio_type', models.CharField(default=None, max_length=50, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('audio_file', models.FileField(max_length=250, upload_to=radio.models.get_audio_path)),
                ('encrypted', models.BooleanField(db_index=True, default=False)),
                ('emergency', models.BooleanField(db_index=True, default=False)),
                ('units', models.JSONField(blank=True, default=list)),
                ('frequencys', models.JSONField(blank=True, default=list)),
                ('frequency', models.FloatField(default=0.0)),
                ('length', models.FloatField(default=0.0, null=True)),
                ('locked', models.BooleanField(db_index=True, default=False)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('recorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.systemrecorder')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.system')),
                ('talkgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.talkgroup')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TalkGroupACL',
            fields=[
                ('UUID', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('default_new_talkgroups', models.BooleanField(default=True)),
                ('default_new_users', models.BooleanField(default=True)),
                ('download_allowed', models.BooleanField(default=True)),
                ('transcript_allowed', models.BooleanField(default=True)),
                ('allowed_talkgroups', models.ManyToManyField(to='radio.talkgroup')),
                ('users', models.ManyToManyField(to='radio.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='systemrecorder',
            name='talkgroups_allowed',
            field=models.ManyToManyField(blank=True, related_name='SRTGAllow', to='radio.talkgroup'),
        ),
        migrations.AddField(
            model_name='systemrecorder',
            name='talkgroups_denyed',
            field=models.ManyToManyField(blank=True, related_name='SRTGDeny', to='radio.talkgroup'),
        ),
        migrations.AddField(
            model_name='systemrecorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radio.userprofile'),
        ),
        migrations.CreateModel(
            name='SystemForwarder',
            fields=[
                ('UUID', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('recorder_key', models.UUIDField()),
                ('remote_url', models.CharField(max_length=250)),
                ('forward_incidents', models.BooleanField(default=False)),
                ('forwarded_systems', models.ManyToManyField(to='radio.system')),
                ('talkgroup_filter', models.ManyToManyField(blank=True, to='radio.talkgroup')),
            ],
        ),
        migrations.CreateModel(
            name='SystemACL',
            fields=[
                ('UUID', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('public', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(blank=True, to='radio.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='system',
            name='systemACL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.systemacl'),
        ),
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('UUID', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('public', models.BooleanField(default=True)),
                ('community_shared', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.userprofile')),
                ('scanlists', models.ManyToManyField(to='radio.scanlist')),
            ],
        ),
        migrations.AddField(
            model_name='scanlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.userprofile'),
        ),
        migrations.AddField(
            model_name='scanlist',
            name='talkgroups',
            field=models.ManyToManyField(to='radio.talkgroup'),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('UUID', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('agency', models.ManyToManyField(blank=True, to='radio.agency')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.system')),
                ('transmission', models.ManyToManyField(blank=True, to='radio.transmission')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.AddField(
            model_name='agency',
            name='city',
            field=models.ManyToManyField(blank=True, to='radio.city'),
        ),
    ]
