# Generated by Django 3.2.10 on 2022-03-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_auto_20220313_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkgroupacl',
            name='transcript_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useralert',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Number of Transmissions over trigger time to alert'),
        ),
        migrations.AddField(
            model_name='useralert',
            name='trigger_time',
            field=models.IntegerField(default=10, verbose_name='trigger time'),
        ),
    ]
