# Generated by Django 3.2.10 on 2022-04-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_auto_20220316_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmission',
            name='audio_type',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
