# Generated by Django 3.2.10 on 2022-07-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0007_auto_20220530_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='rr_system_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
