version: 2.1
orbs: # adds orbs to your configuration
  jira: circleci/jira@1.3.1 # invokes the Jira orb, making its commands accessible
workflows:
  build:
    jobs:
      - build:
          post-steps:
            - jira/notify 
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:20.10-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk update && \
            apk add  --upgrade --no-cache \
              py-pip=9.0.0-r1 \
              jq \
              curl
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76

      - run:
          name: Build trunkplayer-NG Docker image
          command: |
            docker build  -t trunkplayer/trunkplayer-ng:${CIRCLE_BRANCH} .
            docker build  -t trunkplayer/trunkplayer-ng:${CIRCLE_SHA1} .
      - run:
          name: Build nginx Docker image
          command: |
            docker build  -t trunkplayer/trunkplayer-ng-nginx:${CIRCLE_BRANCH} nginx/
            docker build  -t trunkplayer/trunkplayer-ng-nginx:${CIRCLE_SHA1} nginx/
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push "trunkplayer/trunkplayer-ng-nginx:${CIRCLE_BRANCH}"
            docker push "trunkplayer/trunkplayer-ng:${CIRCLE_SHA1}"
            