version: 2.1
orbs: # adds orbs to your configuration
  jira: circleci/jira@1.3.1 # invokes the Jira orb, making its commands accessible
workflows:
  build:
    jobs:
      - build:
          post-steps:
            - jira/notify 
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - checkout
      
      - run:
          name: Install dependencies
          command: |
            sudo apt update && \
            sudo apt install -y  \
              curl \
              jq \
              git \
              qemu-user-static \
              binfmt-support
      - run: |
          ssh remote-docker \<<EOF
            sudo bash -c 'echo "{\"experimental\": true}" > /etc/docker/daemon.json'
            sudo systemctl restart docker
            sudo docker info
          EOF
      - deploy:
          name: Setup Docker
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker context create multi-arch-build
            docker buildx create --use multi-arch-build
      - run:
          name: Build trunkplayer-NG Docker amd64 image
          command: |
            docker buildx build --platform linux/amd64  -t trunkplayer/trunkplayer-ng:${CIRCLE_BRANCH}  --push .
      - run:
          name: Build trunkplayer-NG Docker arm64 image
          command: |
            docker buildx build --platform linux/arm64  -t trunkplayer/trunkplayer-ng:${CIRCLE_BRANCH}  --push .
      - run:
          name: Build trunkplayer-NG Docker arm/v7 image
          command: |
            docker buildx build --platform linux/arm/v7 -t trunkplayer/trunkplayer-ng:${CIRCLE_BRANCH}  --push .
      - run:
          name: Build trunkplayer-NG Docker arm/v6 image
          command: |
            docker buildx build --platform linux/arm/v6 -t trunkplayer/trunkplayer-ng:${CIRCLE_BRANCH}  --push .   
      - run:
          name: Build nginx Docker image
          command: |
            docker build  -t trunkplayer/trunkplayer-ng-nginx:${CIRCLE_BRANCH} nginx/
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push "trunkplayer/trunkplayer-ng-nginx:${CIRCLE_BRANCH}"
            docker push "trunkplayer/trunkplayer-ng:${CIRCLE_BRANCH}"
            