version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Build trunkplayer-NG Docker image
          command: |
            docker build  -t maxwelldps/trunkplayer-ng:rolling .
            docker build  -t maxwelldps/trunkplayer-ng:${CIRCLE_SHA1} .
      - run:
          name: Build nginx Docker image
          command: |
            docker build  -t maxwelldps/trunkplayer-ng-nginx:rolling nginx/
            docker build  -t maxwelldps/trunkplayer-ng-nginx:${CIRCLE_SHA1} nginx/
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push "maxwelldps/trunkplayer-ng-nginx:rolling"
            docker push "maxwelldps/trunkplayer-ng:${CIRCLE_SHA1}"
            