version: 2.1
orbs: # adds orbs to your configuration
  jira: circleci/jira@1.3.1 # invokes the Jira orb, making its commands accessible
workflows:
  build:
    jobs:
      - build:
          post-steps:
            - jira/notify 
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:20.10-git
    steps:
      - setup_remote_docker:
          version: 19.03.14
      - checkout
      
      - run:
          name: Install dependencies
          command: |
            apk update && \
            apk add  --upgrade --no-cache \
              curl \
              jq 
      - run: |
          ssh remote-docker \<<EOF
            sudo bash -c 'echo "{\"experimental\": true}" > /etc/docker/daemon.json'
            sudo systemctl restart docker
            sudo docker info
          EOF
      - run:
          name: Build trunkplayer-NG Docker image
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6  -t trunkplayer/trunkplayer-ng:${CIRCLE_BRANCH}  --push .
          
      - run:
          name: Build nginx Docker image
          command: |
            docker build  -t trunkplayer/trunkplayer-ng-nginx:${CIRCLE_BRANCH} nginx/
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push "trunkplayer/trunkplayer-ng-nginx:${CIRCLE_BRANCH}"
            docker push "trunkplayer/trunkplayer-ng:${CIRCLE_BRANCH}"
            