# Generated by Django 4.2.10 on 2024-02-11 23:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('radio', '0002_transmission_has_tones_transmission_is_dispatch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MqttServer',
            fields=[
                ('UUID', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=1883)),
                ('keepalive', models.IntegerField(default=60)),
                ('enabled', models.BooleanField(default=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('agencies', models.ManyToManyField(blank=True, to='radio.agency')),
                ('systems', models.ManyToManyField(blank=True, to='radio.system')),
            ],
        ),
    ]
