# Generated by Django 3.2.8 on 2021-12-28 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanner",
            name="communityShared",
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name="agency",
            name="city",
        ),
        migrations.AddField(
            model_name="agency",
            name="city",
            field=models.ManyToManyField(blank=True, to="radio.City"),
        ),
        migrations.AlterField(
            model_name="systemreciverate",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 12, 27, 19, 59, 24, 167970)
            ),
        ),
    ]
