# Generated by Django 3.2.10 on 2022-02-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkgroup',
            name='mode',
            field=models.CharField(choices=[('digital', 'Digital'), ('analog', 'Analog'), ('tdma', 'TDMA'), ('mixed', 'Mixed')], default='digital', max_length=250),
        ),
    ]
