# Generated by Django 3.2.8 on 2021-12-29 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_auto_20211227_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemreciverate',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 28, 18, 14, 54, 38177)),
        ),
        migrations.AlterField(
            model_name='talkgroup',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
