# Generated by Django 3.2.10 on 2022-01-03 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_auto_20211231_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='pruneTransmissions',
            field=models.BooleanField(default=False, verbose_name='Enable Pruneing Transmissions'),
        ),
        migrations.AddField(
            model_name='system',
            name='pruneTransmissionsAfterDays',
            field=models.IntegerField(default=365, verbose_name='Days to keep Transmissions (Prune)'),
        ),
        migrations.AlterField(
            model_name='systemreciverate',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 9, 5, 55, 767396)),
        ),
    ]
