# Generated by Django 3.2.10 on 2022-03-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_rename_emergencyonly_useralert_emergency_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkgroupacl',
            name='default_new_talkgroups',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='useralert',
            name='app_rise_urls',
            field=models.TextField(blank=True, default='', verbose_name=', Seperated AppriseURL(s)'),
        ),
    ]
