# Generated by Django 3.2.10 on 2022-01-08 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_auto_20220107_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmission',
            name='transscript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemreciverate',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 7, 17, 10, 13, 967545)),
        ),
    ]
