# Generated by Django 3.2.8 on 2021-12-29 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_auto_20211228_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemreciverate',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 28, 18, 35, 3, 132996)),
        ),
        migrations.AlterField(
            model_name='talkgroup',
            name='alphaTag',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
