# Generated by Django 3.2.8 on 2021-12-30 03:21

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0005_auto_20211229_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemreciverate',
            name='id',
        ),
        migrations.AddField(
            model_name='systemreciverate',
            name='UUID',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='systemreciverate',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 29, 19, 21, 19, 102238)),
        ),
    ]
