# Generated by Django 3.2.10 on 2022-01-11 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0005_auto_20220109_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemforwarder',
            name='talkGroupFilter',
            field=models.ManyToManyField(to='radio.TalkGroup'),
        ),
        migrations.AlterField(
            model_name='systemreciverate',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 15, 1, 38, 273052)),
        ),
    ]
