# Generated by Django 3.2.8 on 2021-11-02 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0006_auto_20211102_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='trunkRecorderID',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='transmission',
            field=models.ManyToManyField(blank=True, to='radio.Transmission'),
        ),
        migrations.AlterField(
            model_name='systemreciverate',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 22, 29, 25, 320000)),
        ),
    ]
