# Generated by Django 3.2.10 on 2022-01-15 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radio", "0006_auto_20220111_1501"),
    ]

    operations = [
        migrations.AddField(
            model_name="talkgroup",
            name="mode",
            field=models.CharField(
                choices=[
                    ("digital", "Digital"),
                    ("analog", "Analog"),
                    ("tdma", "TDMA"),
                ],
                default="digital",
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="systemreciverate",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 1, 15, 9, 17, 41, 902108)
            ),
        ),
    ]
