# Generated by Django 3.2.10 on 2022-02-03 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0007_auto_20220115_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='useralert',
            name='body',
            field=models.CharField(default='New Activity on %T - %I', max_length=255),
        ),
        migrations.AddField(
            model_name='useralert',
            name='emergencyOnly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useralert',
            name='title',
            field=models.CharField(default='New Activity Alert', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemforwarder',
            name='talkGroupFilter',
            field=models.ManyToManyField(blank=True, to='radio.TalkGroup'),
        ),
        migrations.AlterField(
            model_name='systemreciverate',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 19, 4, 19, 347202)),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='audioFile',
            field=models.FileField(upload_to='audio/%Y/%m/%d/'),
        ),
    ]
