# Generated by Django 3.2.8 on 2021-11-02 22:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0007_auto_20211102_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='agency',
            field=models.ManyToManyField(blank=True, to='radio.Agency'),
        ),
        migrations.AlterField(
            model_name='systemreciverate',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 22, 38, 4, 518144)),
        ),
        migrations.AlterField(
            model_name='systemrecorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radio.userprofile'),
        ),
    ]
