# Generated by Django 3.2.10 on 2022-02-03 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0008_auto_20220202_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemreciverate',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 19, 26, 45, 296867)),
        ),
        migrations.AlterField(
            model_name='useralert',
            name='body',
            field=models.TextField(default='New Activity on %T - %I'),
        ),
    ]
