# Generated by Django 3.2.10 on 2022-02-05 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0009_auto_20220202_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='useralert',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='systemreciverate',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 20, 36, 58, 822686)),
        ),
    ]
