# Generated by Django 3.2.8 on 2021-11-26 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radio", "0009_auto_20211126_0848"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemreciverate",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 11, 26, 9, 6, 35, 860339)
            ),
        ),
    ]
