# Generated by Django 3.2.8 on 2021-11-28 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0012_auto_20211128_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemreciverate',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 28, 8, 49, 9, 303722)),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='audioFile',
            field=models.FileField(upload_to=''),
        ),
    ]
