# Generated by Django 3.2.8 on 2021-12-24 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0017_alter_systemreciverate_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemreciverate',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 9, 6, 13, 375749)),
        ),
    ]
